# Generated by Django 4.1.3 on 2022-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForNlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_day',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_month',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_year',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
