# Generated by Django 4.1.3 on 2022-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForNlp', '0002_comment_comment_day_comment_comment_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person_id',
            field=models.CharField(default=0, max_length=2000),
        ),
    ]
